### PR TITLE
Fix boss summon bypass

### LINKED ISSUE #3243: added more boss id in getdatahandler
not all boss are listed in MPAllowedEnemies like plantera, skeletron, lunatic and wof its possible to add this in getdatahandler?

### PR DESCRIPTION
**Pull request by Reisenbug**
Block Plantera summon by preventing Plantera Bulb destruction without `summonboss` permission
Sync Old Man NPC state back to client when Skeletron summon is rejected
Block Wall of Flesh summon by intercepting Guide Voodoo Doll item drop without `summonboss` permission

Note: 
For wof:
when blocked, the Guide Voodoo Doll is already consumed and will not be returned to the player; wof summon via Guide NPC dying in lava and voodoo doll dropped by voodoo demons naturally are not covered by this fix. If you have an alternative feel free to present

For Plantera:
From wiki:
image
The protection behaves like a region — all methods except lava contact are covered, as lava-triggered destruction is server-side and cannot be intercepted(flowing lava can also destroy protected region)
Fixes #3243 

btw I can't summon cultist or skeletron without permission

### CODE REVIEW

**Comment by Reisenbug** [comment]
@greptile review

File: TShockAPI/Bouncer.cs [hunk 1]
```diff
@@ -1269,6 +1266,15 @@ internal void OnItemDrop(object sender, GetDataHandlers.ItemDropEventArgs args)
 				args.Handled = true;
 				return;
 			}
+
+			if (type == ItemID.GuideVoodooDoll && pos.Y / 16f >= Main.maxTilesY - 205 && !args.Player.HasPermission(Permissions.summonboss))
```
Comment (ACaiCat) [inline TShockAPI/Bouncer.cs]: Replace magic height condithon with `ZoneUnderworldHeight`
```suggestion
			if (type == ItemID.GuideVoodooDoll && args.Player.TPlayer.ZoneUnderworldHeight && !args.Player.HasPermission(Permissions.summonboss))
```

File: TShockAPI/Bouncer.cs [hunk 2]
```diff
@@ -685,6 +672,18 @@ internal void OnTileEdit(object sender, GetDataHandlers.TileEditEventArgs args)
 					return;
 				}
 
+				if (action == EditAction.KillTile && Main.tile[tileX, tileY].type == TileID.PlanteraBulb)
```
Comment (ACaiCat) [inline TShockAPI/Bouncer.cs]: It doesn't work when the player destroyed the tile under the Plantera bulb

**Comment by hakusaro** [comment]
@greptile review

File: TShockAPI/Bouncer.cs [hunk 3]
```diff
@@ -672,6 +672,25 @@ internal void OnTileEdit(object sender, GetDataHandlers.TileEditEventArgs args)
...
+						if (!args.Player.HasPermission(Permissions.summonboss))
+						{
+							TShock.Log.ConsoleDebug(GetString("Bouncer / OnTileEdit rejected Plantera bulb destroy from {0}", args.Player.Name));
+							args.Player.SendErrorMessage(GetString("You do not have permission to summon Plantera."));
+							args.Player.SendTileSquareCentered(tileX, tileY, 4);
+							args.Handled = true;
+							return;
+						}
+					}
+				}
```
[the remark this answers is not in the document]
Comment (Reisenbug) [reply TShockAPI/Bouncer.cs:704]: The support tile at Y+1 always has a block (mud block with jungle grass), so replacing the tile there without spawning the boss seems impossible. I think no action filter is needed

**Review by ACaiCat — APPROVED** [review]
