### PR TITLE
Fix rope coils.

### LINKED ISSUE #1670: Rope Coils unable to be placed when only one is in the selected stack
* TShock version: 4.3.26

#### Reproduction steps

Select stack with exactly one (Silk/Vine/Web) Rope Coil.
Throw rope coil at vertical column of blocks

Expected:
- (Silk/Vine/Web) Rope Coil entity is thrown.
- (Silk/Vine/Web) Rope Coil is placed upon collision with solid blocks.
- Excess (Silk/Vine/Web) Rope is returned as dropped items.

Reality:
- (Silk/Vine/Web) Rope Coil entity is thrown.
- (Silk/Vine/Web) Rope Coil entity disappears upon collision with solid blocks.
- What would have been excess (Silk/Vine/Web) Rope had the coil been placed is returned as dropped items.

#### Notes
- `/group addperm <group> tshock.ignore.*` does not appear to change this.

### LINKED ISSUE #1834: [Bouncer] Snake Charmer's Flute Doesn't Work.
* TShock version: 4.4.0.0 Pre6

#### Reproduction steps (if applicable)?

1. Use the 'Snake Charmers Flute'
2. Wait for the Snake to finish rising.
3. Supposed to place as rope but vanishes leaving behind the pot.

#### Any screenshots?

image
image

### PR DESCRIPTION
**Pull request by Olink**
Fixes #1670, fixes #1834.

### CODE REVIEW

File: TShockAPI/PlayerData.cs [hunk 1]
```diff
@@ -496,7 +496,7 @@ public void RestoreCharacter(TSPlayer player)
 					}
 
 					var response = NetCreativeUnlocksModule.SerializeItemSacrifice(i, amount);
-					NetManager.Instance.SendToClient(response, player.TPlayer.whoAmI);
+					NetManager.Instance.SendToClient(response, player.Index);
```
Comment (Olink) [inline TShockAPI/PlayerData.cs:499]: Just a cleanup I saw while I was browsing.  This shouldn't be a functional change, but a consistency change.

**Review by QuiCM — APPROVED** [review]
LGTM
